In [1]:
import numpy as np

# To create numpy arrays from list

In [7]:
list_1 = [1,2,3,4,5]

In [8]:
np_arr = np.array(list_1)
np_arr

array([1, 2, 3, 4, 5])

In [9]:
#To create 2-D array

In [10]:
list_2 = [[1,2,3], [4,5,6], [7,8,9]]
np_arr = np.array(list_2)

In [11]:
np_arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Generate array

In [12]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

To get array of numbers with specific interval/

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

# Get evenly certain number of spaced numbers within an interval

In [16]:
#Returns 20 numbers between range 0 to 10
np.linspace(0,10,20)

array([  0.        ,   0.52631579,   1.05263158,   1.57894737,
         2.10526316,   2.63157895,   3.15789474,   3.68421053,
         4.21052632,   4.73684211,   5.26315789,   5.78947368,
         6.31578947,   6.84210526,   7.36842105,   7.89473684,
         8.42105263,   8.94736842,   9.47368421,  10.        ])

# Create Identity matrix

In [17]:
np.eye(6)

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]])

# Random Numbers from Uniform Distribution

In [18]:
np.random.rand(5)

array([ 0.49968524,  0.08529592,  0.87290041,  0.18057001,  0.9684561 ])

In [19]:
np.random.rand(3,5)

array([[ 0.44489439,  0.00769919,  0.8074338 ,  0.54676155,  0.26193636],
       [ 0.96877486,  0.84304393,  0.54694152,  0.39515732,  0.90484562],
       [ 0.03484258,  0.57980078,  0.51965698,  0.05230348,  0.92552064]])

# Create random numbers from Gaussian distribution

In [20]:
np.random.randn(10)

array([-0.44000458,  0.30218392,  2.10629936, -1.63947091, -1.25840409,
       -0.46555941,  0.29472338,  1.34963867, -0.01018193, -0.58518498])

In [21]:
np.random.randn(2,3)

array([[ 0.74649301, -0.0324867 , -1.41213061],
       [ 0.91318814,  0.58342507,  0.0475116 ]])

# Generate random integer from high to low

In [22]:
np.random.randint(1,100)

21

In [23]:
#create 10 random integers from 1 to 100
np.random.randint(1,101,10)

array([14, 40, 26, 87,  2, 49,  9, 85, 30, 41])

# Reshape

In [24]:
arr_1 =np.arange(20)

In [28]:
arr_2 = np.random.randint(0,50,10)
arr_2

array([36, 37, 20, 21, 38,  8, 14, 34, 17, 35])

In [29]:
arr_1.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

# Get max value in an array 

In [30]:
arr_2.max()

38

# Get min value in an array

In [31]:
arr_2.min()

8

# Get Index of maximum value in an array

In [32]:
arr_2.argmax()

4

# Get Index of minimum value in an array

In [34]:
arr_2.argmin()

5

# Get shape of an array

In [35]:
arr_1.shape

(20,)

In [36]:
#The above output indicates that it is a 1-D array. 
#Let's reshape
arr_1 = arr_1.reshape(5,4)

In [37]:
arr_1.shape

(5, 4)

# Get datatype within array

In [38]:
arr_1.dtype

dtype('int32')

# Index and Selection 

In [39]:
arr_in = np.arange(0,11)

In [40]:
arr_in

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
arr_in[7]

7

In [43]:
#To get range of values
arr_in[5:9]

array([5, 6, 7, 8])

In [44]:
#to grab everything from start to end
arr_in[5:]

array([ 5,  6,  7,  8,  9, 10])

In [45]:
#Broadcast values
arr_in[0:5] = 50

In [46]:
arr_in

array([50, 50, 50, 50, 50,  5,  6,  7,  8,  9, 10])

In [50]:
#Numpy slice
sl_arr = arr_in[0:5]
sl_arr

array([50, 50, 50, 50, 50])

In [51]:
sl_arr[:] = 200

In [52]:
sl_arr

array([200, 200, 200, 200, 200])

In [53]:
arr_in

array([200, 200, 200, 200, 200,   5,   6,   7,   8,   9,  10])

In [54]:
#The change has been refelected in the original array. It just uses references and does not create its own copy of data

# Copy array to avoid reference

In [56]:
arr_in

array([200, 200, 200, 200, 200,   5,   6,   7,   8,   9,  10])

In [57]:
arr_in_cpy = arr_in.copy()
arr_in_cpy

array([200, 200, 200, 200, 200,   5,   6,   7,   8,   9,  10])

In [58]:
arr_in_cpy[0:5] = 0

In [59]:
arr_in_cpy

array([ 0,  0,  0,  0,  0,  5,  6,  7,  8,  9, 10])

In [60]:
arr_in

array([200, 200, 200, 200, 200,   5,   6,   7,   8,   9,  10])

In [61]:
#It can be noted that the above result affect only the copied array not the original

# Index 2D array or matrix

In [62]:
arr_2d = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [63]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
#To get '1'
arr_2d[0][1]

2

In [65]:
#To get first row
arr_2d[0]

array([1, 2, 3])

In [66]:
#Other way
arr_2d[0,1]

2

In [67]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

# Array Comparison

In [68]:
arr_3 = np.arange(1,11)

In [69]:
arr_3 > 5

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

It returns array of true or false value

In [70]:
arr_3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [72]:
#To save that
boo_arr_3 = arr_3 > 5
boo_arr_3

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [73]:
arr_3[boo_arr_3]

array([ 6,  7,  8,  9, 10])

This will return the value where there is 'true' in boolean array

In [74]:
#Conditional selection
arr_3[arr_3 > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

# Numpy Operations

In [85]:
arr_1 = np.arange(0,11)
arr_1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

To add element by element basis

In [86]:
arr_1 + arr_1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

Subtract


In [87]:
arr_1 - arr_1

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Multiplication

In [88]:
arr_1 * arr_1

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [89]:
#Scalar addition
arr_1 + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [90]:
#Dividing by zero will give 'nan' not error

In [92]:
arr_1 / arr_1

C:\Users\saish\Anaconda2\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [93]:
1 / arr_1

C:\Users\saish\Anaconda2\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111,
        0.1       ])

# Universal Array Functions

In [94]:
#Square root
np.sqrt(arr_1)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [96]:
#for exponent 
np.exp(arr_1)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [97]:
np.max(arr_1)

10

In [98]:
np.sin(arr_1)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [99]:
np.log(arr_1)

C:\Users\saish\Anaconda2\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458,
        2.30258509])